services:
  db:
    image:postgres:15-alpine
  container_name: blog-db
  restart: always
  volumes:
    - pgdata:/var/lib/postgresql/data
      # -./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  environment:
    POSTGRES_DB: symfony_db
    POSTGRES_USER: symfony_user
    POSTGRES_PASSWORD: symfony_pass
  ports:
    - "5432:5432"

  backend:
    build:
      context: ./backend
    container_name: blog-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://symfony:symfony@db:5432/symfony

  frontend:
    build:
      context: ./frontend
    container_name: blog-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true

  java-client:
    build:
      context: ./java-client
    container_name: blog-java-client
    # A activer quand le JAR sera pret
    # command: ["java", "-jar", "client.jar"]

  volumes:
    postgre-data:
